# Generated by Django 5.2.7 on 2025-11-05 22:20

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='idx_orderitem_order_only_2'),
        ),
    ]
