# Generated by Django 5.2.7 on 2025-11-05 22:21

from django.db import migrations
from django.contrib.postgres.operations import RemoveIndexConcurrently


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('shop', '0002_orderitem_idx_orderitem_order_only_2'),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name='orderitem',
            name='idx_orderitem_order_only_2',
        ),
    ]
